In [1]:
import sys
sys.path.append('C:/Users/puent/OneDrive/Escritorio/Javi Bootcamp/Data-Science-TBB-main/SCRIPTS/Proyectos/Machine Learning/src/utils')
from  funciones import ConcatenarCSV, guardar_csv
import pandas as pd

from sklearn.preprocessing import LabelEncoder

print("Packages installed")

Packages installed

In [4]:
ruta = r'C:/Users/puent/OneDrive/Escritorio/Javi Bootcamp/Data-Science-TBB-main/SCRIPTS/Proyectos/Machine Learning/src/data/raw/'

In [6]:
tenis_df = ConcatenarCSV(ruta)

3

In [7]:
tenis_df.head(10)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0
5,2021-0096,Tokyo Olympics,Hard,64,A,20210724,242,105062,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,123.0,652.0,62.0,1063.0
6,2021-0096,Tokyo Olympics,Hard,64,A,20210724,243,136440,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,57.0,1153.0,80.0,916.0
7,2021-0096,Tokyo Olympics,Hard,64,A,20210724,244,200175,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,1309.0,115.0,722.0
8,2021-0096,Tokyo Olympics,Hard,64,A,20210724,245,106218,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,64.0,1047.0,98.0,812.0
9,2021-0096,Tokyo Olympics,Hard,64,A,20210724,246,106078,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,79.0,926.0,102.0,779.0

In [8]:
tenis_df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')

## Procesamos los datos para limpiarlos de nulos y efectuar el modelo

Procedemos a eliminar las características que son redundantes o están correlacionadas entre sí, y aquellas que obviamente no están disponibles antes de un partido para predecir.

"winner_name", "loser_name" y "tourney_name" porque son casi redundantes y pueden ser reemplazadas respectivamente por "winner_id", "loser_id" y "tourney_id".

Las características "minutes", "score", "1stIn", "_1stWon", "SvGms", "l_bpFaced", "l_bpSaved" y "svpt" porque no pueden ser conocidas de antemano.

In [9]:
df = tenis_df.drop(columns=['score','tourney_name','winner_name',
                      'loser_name','minutes', 'l_1stIn', 'l_1stWon', 'l_2ndWon','l_ace', 'l_svpt',
                      'l_SvGms','l_bpFaced','l_df', 'l_bpSaved',  'w_1stIn', 'w_1stWon','w_2ndWon', 'w_SvGms',
                      'w_ace', 'w_svpt','w_bpFaced', 'w_bpSaved','w_df'])
print("columnas restantes:  ", df.columns)

columnas restantes:   Index(['tourney_id', 'surface', 'draw_size', 'tourney_level', 'tourney_date',
       'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_hand',
       'winner_ht', 'winner_ioc', 'winner_age', 'loser_id', 'loser_seed',
       'loser_entry', 'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age',
       'best_of', 'round', 'winner_rank', 'winner_rank_points', 'loser_rank',
       'loser_rank_points'],
      dtype='object')

Buscamos los valores nulos en las columnas y los eliminamos

In [10]:
porcentaje_nulos = df.isnull().sum() * 100 / len(df)
nulos_df = pd.DataFrame({'Columna': df.columns, 'Numero de valores nulos': df.isnull().sum(),
                                 'Porcentaje de nulos': porcentaje_nulos})
print(nulos_df.reset_index().drop(columns=['index']))

               Columna  Numero de valores nulos  Porcentaje de nulos
0           tourney_id                        0             0.000000
1              surface                       53             0.613710
2            draw_size                        0             0.000000
3        tourney_level                        0             0.000000
4         tourney_date                        0             0.000000
5            match_num                        0             0.000000
6            winner_id                        0             0.000000
7          winner_seed                     5001            57.908754
8         winner_entry                     7318            84.738305
9          winner_hand                        2             0.023159
10           winner_ht                      282             3.265401
11          winner_ioc                        0             0.000000
12          winner_age                        4             0.046318
13            loser_id                        0             0.000000
14          loser_seed                     6469            74.907365
15         loser_entry                     6652            77.026401
16          loser_hand                        1             0.011579
17            loser_ht                      522             6.044465
18           loser_ioc                        0             0.000000
19           loser_age                       12             0.138953
20             best_of                        0             0.000000
21               round                        0             0.000000
22         winner_rank                       36             0.416860
23  winner_rank_points                       36             0.416860
24          loser_rank                       77             0.891616
25   loser_rank_points                       77             0.891616

### Eliminamos las columnas con muchos nulos

In [11]:
cols_eliminar =nulos_df[nulos_df['Porcentaje de nulos'] > 55]

In [12]:
cols_eliminar

                   Columna  Numero de valores nulos  Porcentaje de nulos
winner_seed    winner_seed                     5001            57.908754
winner_entry  winner_entry                     7318            84.738305
loser_seed      loser_seed                     6469            74.907365
loser_entry    loser_entry                     6652            77.026401

In [13]:
df = df.drop(columns=cols_eliminar['Columna'].values)

### Eliminamos los valores nulos de las columnas que quedan

In [14]:
# Eliminamos todas las filas con valores nulos
df.dropna(subset=['winner_rank_points', 'loser_rank_points','winner_rank','loser_rank', 'surface', 'winner_age', 'loser_ht', 'surface', 'loser_ht'], inplace=True)
df = df.reset_index(drop=True)
df= df.dropna()
df.head(15)

,tourney_id,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_hand,winner_ht,winner_ioc,...,loser_hand,loser_ht,loser_ioc,loser_age,best_of,round,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Hard,64,A,20210724,237,126207,R,188.0,USA,...,R,180.0,KOR,23.6,3,R64,53.0,1228.0,71.0,996.0
1,2021-0096,Hard,64,A,20210724,238,105526,R,193.0,GER,...,L,183.0,BRA,27.1,3,R64,48.0,1410.0,95.0,829.0
2,2021-0096,Hard,64,A,20210724,239,111576,R,178.0,IND,...,R,188.0,UZB,34.8,3,R64,160.0,471.0,197.0,354.0
3,2021-0096,Hard,64,A,20210724,240,105357,R,183.0,AUS,...,R,185.0,ITA,19.3,3,R64,44.0,1476.0,61.0,1106.0
4,2021-0096,Hard,64,A,20210724,241,207830,R,183.0,CZE,...,R,185.0,POR,32.3,3,R64,145.0,525.0,137.0,570.0
5,2021-0096,Hard,64,A,20210724,242,105062,R,183.0,KAZ,...,R,180.0,ARG,29.3,3,R64,123.0,652.0,62.0,1063.0
6,2021-0096,Hard,64,A,20210724,243,136440,L,180.0,GER,...,L,183.0,ARG,31.3,3,R64,57.0,1153.0,80.0,916.0
7,2021-0096,Hard,64,A,20210724,244,200175,R,183.0,SRB,...,R,183.0,POL,25.5,3,R64,50.0,1309.0,115.0,722.0
8,2021-0096,Hard,64,A,20210724,245,106218,R,180.0,USA,...,R,193.0,SVK,30.9,3,R64,64.0,1047.0,98.0,812.0
9,2021-0096,Hard,64,A,20210724,246,106078,R,196.0,BLR,...,R,183.0,FRA,36.5,3,R64,79.0,926.0,102.0,779.0
10,2021-0096,Hard,64,A,20210724,247,123755,R,191.0,COL,...,R,183.0,EGY,30.8,3,R64,113.0,727.0,171.0,424.0
11,2021-0096,Hard,64,A,20210724,248,105902,R,183.0,AUS,...,R,193.0,SVK,23.3,3,R64,77.0,933.0,246.0,268.0
12,2021-0096,Hard,64,A,20210724,249,105227,R,198.0,CRO,...,R,185.0,BRA,24.5,3,R64,36.0,1705.0,217.0,319.0
13,2021-0096,Hard,64,A,20210724,250,104871,R,188.0,FRA,...,R,191.0,CHI,23.6,3,R64,68.0,1019.0,195.0,362.0
14,2021-0096,Hard,64,A,20210724,251,106281,L,183.0,GBR,...,R,185.0,ARG,22.9,3,R64,142.0,538.0,116.0,698.0

In [15]:
df.shape

(7891, 22)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7891 entries, 0 to 8080
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          7891 non-null   object
 1   surface             7891 non-null   object
 2   draw_size           7891 non-null   int64
 3   tourney_level       7891 non-null   object
 4   tourney_date        7891 non-null   int64
 5   match_num           7891 non-null   int64
 6   winner_id           7891 non-null   int64
 7   winner_hand         7891 non-null   object
 8   winner_ht           7891 non-null   float64
 9   winner_ioc          7891 non-null   object
 10  winner_age          7891 non-null   float64
 11  loser_id            7891 non-null   int64
 12  loser_hand          7891 non-null   object
 13  loser_ht            7891 non-null   float64
 14  loser_ioc           7891 non-null   object
 15  loser_age           7891 non-null   float64
 16  best_of             7891 non-null   int64
 17  round               7891 non-null   object
 18  winner_rank         7891 non-null   float64
 19  winner_rank_points  7891 non-null   float64
 20  loser_rank          7891 non-null   float64
 21  loser_rank_points   7891 non-null   float64
dtypes: float64(8), int64(6), object(8)
memory usage: 1.4+ MB

In [17]:
df

,tourney_id,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_hand,winner_ht,winner_ioc,...,loser_hand,loser_ht,loser_ioc,loser_age,best_of,round,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Hard,64,A,20210724,237,126207,R,188.0,USA,...,R,180.0,KOR,23.6,3,R64,53.0,1228.0,71.0,996.0
1,2021-0096,Hard,64,A,20210724,238,105526,R,193.0,GER,...,L,183.0,BRA,27.1,3,R64,48.0,1410.0,95.0,829.0
2,2021-0096,Hard,64,A,20210724,239,111576,R,178.0,IND,...,R,188.0,UZB,34.8,3,R64,160.0,471.0,197.0,354.0
3,2021-0096,Hard,64,A,20210724,240,105357,R,183.0,AUS,...,R,185.0,ITA,19.3,3,R64,44.0,1476.0,61.0,1106.0
4,2021-0096,Hard,64,A,20210724,241,207830,R,183.0,CZE,...,R,185.0,POR,32.3,3,R64,145.0,525.0,137.0,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8073,2023-M-DC-2023-WG1-PO-IND-DEN-01,Hard,4,D,20230203,4,208029,R,185.0,DEN,...,R,178.0,IND,25.4,3,RR,9.0,3046.0,506.0,70.0
8075,2023-M-DC-2023-WG2-M-IND-MAR-01,Hard,4,D,20230916,2,111576,R,178.0,IND,...,R,191.0,SUI,28.3,3,RR,156.0,397.0,779.0,29.0
8078,2023-M-DC-2023-WG2-M-MON-ECU-01,Clay,4,D,20230915,2,200031,R,185.0,MON,...,R,185.0,ECU,31.7,3,RR,452.0,97.0,185.0,326.0
8079,2023-M-DC-2023-WG2-M-URU-EGY-01,Clay,4,D,20230916,1,105633,R,183.0,EGY,...,R,178.0,ARG,24.1,3,RR,463.0,93.0,828.0,24.0
8080,2023-M-DC-2023-WG2-M-URU-EGY-01,Clay,4,D,20230916,2,105747,R,175.0,EGY,...,L,185.0,URU,23.5,3,RR,721.0,37.0,674.0,44.0

## Feature engeenering

### Nos cargamos la columna de fecha y la dividimos por partes

In [18]:
df['tourney_year'] = df.tourney_date.astype(str).str[:4].astype(int)
df['tourney_month'] = df.tourney_date.astype(str).str[4:6].astype(int)
df['tourney_day'] = df.tourney_date.astype(str).str[6:8].astype(int)
df = df.drop(columns=['tourney_date'])

In [19]:
df

,tourney_id,surface,draw_size,tourney_level,match_num,winner_id,winner_hand,winner_ht,winner_ioc,winner_age,...,loser_age,best_of,round,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_year,tourney_month,tourney_day
0,2021-0096,Hard,64,A,237,126207,R,188.0,USA,23.4,...,23.6,3,R64,53.0,1228.0,71.0,996.0,2021,7,24
1,2021-0096,Hard,64,A,238,105526,R,193.0,GER,31.2,...,27.1,3,R64,48.0,1410.0,95.0,829.0,2021,7,24
2,2021-0096,Hard,64,A,239,111576,R,178.0,IND,23.9,...,34.8,3,R64,160.0,471.0,197.0,354.0,2021,7,24
3,2021-0096,Hard,64,A,240,105357,R,183.0,AUS,32.0,...,19.3,3,R64,44.0,1476.0,61.0,1106.0,2021,7,24
4,2021-0096,Hard,64,A,241,207830,R,183.0,CZE,20.7,...,32.3,3,R64,145.0,525.0,137.0,570.0,2021,7,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8073,2023-M-DC-2023-WG1-PO-IND-DEN-01,Hard,4,D,4,208029,R,185.0,DEN,19.7,...,25.4,3,RR,9.0,3046.0,506.0,70.0,2023,2,3
8075,2023-M-DC-2023-WG2-M-IND-MAR-01,Hard,4,D,2,111576,R,178.0,IND,26.0,...,28.3,3,RR,156.0,397.0,779.0,29.0,2023,9,16
8078,2023-M-DC-2023-WG2-M-MON-ECU-01,Clay,4,D,2,200031,R,185.0,MON,27.0,...,31.7,3,RR,452.0,97.0,185.0,326.0,2023,9,15
8079,2023-M-DC-2023-WG2-M-URU-EGY-01,Clay,4,D,1,105633,R,183.0,EGY,32.9,...,24.1,3,RR,463.0,93.0,828.0,24.0,2023,9,16
8080,2023-M-DC-2023-WG2-M-URU-EGY-01,Clay,4,D,2,105747,R,175.0,EGY,32.4,...,23.5,3,RR,721.0,37.0,674.0,44.0,2023,9,16

In [20]:
df['winner_hand'].value_counts()

winner_hand
R    6921
L     958
U      12
Name: count, dtype: int64

In [21]:
# Eliminar filas donde 'winner_hand' sea 'U'
df = df[df['winner_hand'] != 'U']

In [22]:
df['loser_hand'].value_counts()

loser_hand
R    6760
L    1093
U      26
Name: count, dtype: int64

In [23]:
# Eliminar filas donde 'loser_hand' sea 'U'
df = df[df['loser_hand'] != 'U']

### Codificamos las variables categóricas (object type)

In [24]:
variables_categoricas = ['tourney_id', 'surface', 'tourney_level', 'winner_hand', 'winner_ioc', 'loser_hand', 'loser_ioc', 'round']

In [25]:
label_encoder = LabelEncoder()

for col in variables_categoricas:
    df[col] = label_encoder.fit_transform(df[col])

In [26]:
df.head(15)

,tourney_id,surface,draw_size,tourney_level,match_num,winner_id,winner_hand,winner_ht,winner_ioc,winner_age,...,loser_age,best_of,round,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_year,tourney_month,tourney_day
0,0,2,64,0,237,126207,1,188.0,57,23.4,...,23.6,3,6,53.0,1228.0,71.0,996.0,2021,7,24
1,0,2,64,0,238,105526,1,193.0,27,31.2,...,27.1,3,6,48.0,1410.0,95.0,829.0,2021,7,24
2,0,2,64,0,239,111576,1,178.0,30,23.9,...,34.8,3,6,160.0,471.0,197.0,354.0,2021,7,24
3,0,2,64,0,240,105357,1,183.0,1,32.0,...,19.3,3,6,44.0,1476.0,61.0,1106.0,2021,7,24
4,0,2,64,0,241,207830,1,183.0,16,20.7,...,32.3,3,6,145.0,525.0,137.0,570.0,2021,7,24
5,0,2,64,0,242,105062,1,183.0,34,33.5,...,29.3,3,6,123.0,652.0,62.0,1063.0,2021,7,24
6,0,2,64,0,243,136440,0,180.0,27,27.2,...,31.3,3,6,57.0,1153.0,80.0,916.0,2021,7,24
7,0,2,64,0,244,200175,1,183.0,48,21.8,...,25.5,3,6,50.0,1309.0,115.0,722.0,2021,7,24
8,0,2,64,0,245,106218,1,180.0,57,27.9,...,30.9,3,6,64.0,1047.0,98.0,812.0,2021,7,24
9,0,2,64,0,246,106078,1,196.0,6,28.6,...,36.5,3,6,79.0,926.0,102.0,779.0,2021,7,24
10,0,2,64,0,247,123755,1,191.0,13,25.0,...,30.8,3,6,113.0,727.0,171.0,424.0,2021,7,24
11,0,2,64,0,248,105902,1,183.0,1,29.4,...,23.3,3,6,77.0,933.0,246.0,268.0,2021,7,24
12,0,2,64,0,249,105227,1,198.0,14,32.8,...,24.5,3,6,36.0,1705.0,217.0,319.0,2021,7,24
13,0,2,64,0,250,104871,1,188.0,24,34.4,...,23.6,3,6,68.0,1019.0,195.0,362.0,2021,7,24
14,0,2,64,0,251,106281,0,183.0,25,27.5,...,22.9,3,6,142.0,538.0,116.0,698.0,2021,7,24

In [27]:
len(df)

7853

In [28]:
# Convertir dtypes de int32 a int64
df[['tourney_id', 'surface', 'tourney_year', 'tourney_level', 'winner_hand', 'winner_ioc', 'loser_hand', 'loser_ioc', 'round', 'tourney_month', 'tourney_day']] = df[['tourney_id', 'surface', 'tourney_level', 'tourney_year', 'winner_hand', 'winner_ioc', 'loser_hand', 'loser_ioc', 'round', 'tourney_month', 'tourney_day']].astype('int64')

# Convertir dtypes de float32 a float64
df[['winner_ht', 'winner_age', 'loser_ht', 'loser_age', 'winner_rank', 'winner_rank_points', 'loser_rank']] = df[['winner_ht', 'winner_age', 'loser_ht', 'loser_age', 'winner_rank', 'winner_rank_points', 'loser_rank']].astype('float64')

In [29]:
df.dtypes

tourney_id              int64
surface                 int64
draw_size               int64
tourney_level           int64
match_num               int64
winner_id               int64
winner_hand             int64
winner_ht             float64
winner_ioc              int64
winner_age            float64
loser_id                int64
loser_hand              int64
loser_ht              float64
loser_ioc               int64
loser_age             float64
best_of                 int64
round                   int64
winner_rank           float64
winner_rank_points    float64
loser_rank            float64
loser_rank_points     float64
tourney_year            int64
tourney_month           int64
tourney_day             int64
dtype: object

In [32]:
rutaDFLimpio = r'C:/Users/puent/OneDrive/Escritorio/Javi Bootcamp/Data-Science-TBB-main/SCRIPTS/Proyectos/Machine Learning/src/data/processed'

In [33]:
guardar_csv(df, 'dfLimpio.csv', rutaDFLimpio)

El DataFrame se ha guardado correctamente en 'C:/Users/puent/OneDrive/Escritorio/Javi Bootcamp/Data-Science-TBB-main/SCRIPTS/Proyectos/Machine Learning/src/data/processed/dfLimpio.csv'.