In [33]:
import pandas as pd
import eurostat

In [34]:
# Descargar datos sobre poblaci√≥n total
population_data = eurostat.get_data_df('demo_gind')

# Ver las primeras filas del DataFrame
population = pd.DataFrame(population_data)

link = 'https://ec.europa.eu/eurostat/databrowser/view/DEMO_GIND__custom_7680622/bookmark/table?lang=en&bookmarkId=edacacb0-acad-4876-859f-9549d766826b'

In [35]:
population

,freq,indic_de,geo\TIME_PERIOD,1960,1961,1962,1963,1964,1965,1966,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,AVG,AD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,72419.0,NaN,75486.0,76860.0,NaN,NaN,80562.0,NaN
1,A,AVG,AL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,...,2889095.0,2880694.0,2876092.0,2873458.0,2866376.0,2854191.0,2837848.0,2811667.0,2777689.0,NaN
2,A,AVG,AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3004588.0,2992364.0,2979442.0,2969001.0,2962482.0,2961473.0,NaN,NaN,NaN
3,A,AVG,AT,7047539.0,7086299.0,7129864.0,7175811.0,7223801.0,7270889.0,7322066.0,...,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8916864.0,8955797.0,9041851.0,NaN
4,A,AVG,AZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9535079.0,9649341.0,9757812.0,9854033.0,9939771.0,10024283.0,10093121.0,10137750.0,10141756.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,A,POPTRT,SM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.6,29.5,NaN
1517,A,POPTRT,TR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,33.1,32.5,NaN,NaN,NaN,NaN
1518,A,POPTRT,UA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,42.6,46.6,NaN,NaN
1519,A,POPTRT,UK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.3,35.7,35.6,35.7,34.5,34.8,NaN,NaN,NaN,NaN
1520,A,POPTRT,XK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,34.9,NaN,NaN,NaN

In [36]:
population.rename({'indic_de': 'Demographic indicator'}, axis=1, inplace=True)
population.rename({'geo\TIME_PERIOD': 'Countries'}, axis=1, inplace= True)
population.rename({'freq': 'Frequency'}, axis=1, inplace= True)

In [37]:
countries = {
    "DE_TOT": "Germany including former GDR",
    "EE": "Estonia",
    "IE": "Ireland",
    "EL": "Greece",
    "ES": "Spain",
    "FR": "France",
    "FX": "Metropolitan France",
    "HR": "Croatia",
    "IT": "Italy",
    "CY": "Cyprus",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "HU": "Hungary",
    "MT": "Malta",
    "NL": "Netherlands",
    "AT": "Austria",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "FI": "Finland",
    "SE": "Sweden",
    "EEA31": "European Economic Area (EU28 - 2013-2020 and IS, LI, NO)",
    "EFTA": "European Free Trade Association",
    "IS": "Iceland",
    "LI": "Liechtenstein",
    "NO": "Norway",
    "CH": "Switzerland",
    "UK": "United Kingdom",
    "BA": "Bosnia and Herzegovina",
    "ME": "Montenegro",
    "MD": "Moldova",
    "MK": "North Macedonia",
    "AL": "Albania",
    "RS": "Serbia",
    "TR": "T√ºrkiye",
    "UA": "Ukraine",
    "XK": "Kosovo*",
    "GE": "Georgia",
    "AD": "Andorra",
    "BY": "Belarus",
    "MC": "Monaco",
    "RU": "Russia",
    "SM": "San Marino",
    "AM": "Armenia",
    "AZ": "Azerbaijan"
}

In [38]:
indicators_dict = {
    "AVG": "Average population - total",
    "CNMIGRAT": "Net migration plus statistical adjustment",
    "CNMIGRATRT": "Crude rate of net migration plus statistical adjustment",
    "DEATH": "Deaths - total",
    "FAVG": "Average population - females",
    "FDEATH": "Deaths - females",
    "FJAN": "Population on 1 January - females",
    "FLBIRTH": "Live births - females",
    "GBIRTHRT": "Crude birth rate",
    "GDEATHRT": "Crude death rate",
    "GROW": "Total population change",
    "GROWRT": "Crude rate of total population change",
    "JAN": "Population on 1 January - total",
    "LBIRTH": "Live births - total",
    "MAVG": "Average population - males",
    "MDEATH": "Deaths - males",
    "MIGT": "Sum of immigration and emigration plus statistical adjustment (migration turnover plus statistical adjustment)",
    "MIGTRT": "Crude rate of the sum of immigration and emigration plus statistical adjustment (Crude Rate of migration turnover plus statistical adjustment)",
    "MJAN": "Population on 1 January - males",
    "MLBIRTH": "Live births - males",
    "NATGROW": "Natural change of population",
    "NATGROWRT": "Crude rate of natural change of population",
    "NATT": "Sum of births and deaths (natural turnover)",
    "NATTRT": "Crude rate of sum of births and deaths (crude rate of natural turnover)",
    "POPSHARE": "Population as a percentage of EU28 (2013-2020) population",
    "POPSHARE_EU27_2020": "Population as a percentage of EU27 (from 2020) population",
    "POPT": "Sum of population changes (population turnover)",
    "POPTRT": "Crude rate of sum of population changes(crude rate of population turnover)"
}

In [39]:
population = population.loc[population['Countries'].notna()]

In [40]:
population['Countries'] = population['Countries'].map(countries)

In [41]:
population['Demographic indicator'] = population['Demographic indicator'].map(indicators_dict)

In [42]:
population

,Frequency,Demographic indicator,Countries,1960,1961,1962,1963,1964,1965,1966,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,Average population - total,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,72419.0,NaN,75486.0,76860.0,NaN,NaN,80562.0,NaN
1,A,Average population - total,Albania,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,...,2889095.0,2880694.0,2876092.0,2873458.0,2866376.0,2854191.0,2837848.0,2811667.0,2777689.0,NaN
2,A,Average population - total,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3004588.0,2992364.0,2979442.0,2969001.0,2962482.0,2961473.0,NaN,NaN,NaN
3,A,Average population - total,Austria,7047539.0,7086299.0,7129864.0,7175811.0,7223801.0,7270889.0,7322066.0,...,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8916864.0,8955797.0,9041851.0,NaN
4,A,Average population - total,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9535079.0,9649341.0,9757812.0,9854033.0,9939771.0,10024283.0,10093121.0,10137750.0,10141756.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,A,Crude rate of sum of population changes(crude ...,San Marino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.6,29.5,NaN
1517,A,Crude rate of sum of population changes(crude ...,T√ºrkiye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,33.1,32.5,NaN,NaN,NaN,NaN
1518,A,Crude rate of sum of population changes(crude ...,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,42.6,46.6,NaN,NaN
1519,A,Crude rate of sum of population changes(crude ...,United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.3,35.7,35.6,35.7,34.5,34.8,NaN,NaN,NaN,NaN
1520,A,Crude rate of sum of population changes(crude ...,Kosovo*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,34.9,NaN,NaN,NaN

In [44]:
unique_values = population['Demographic indicator'].unique()
subtables = {}
for value in unique_values:
    subtable = population[population['Demographic indicator'] == value]
    subtables[value] = subtable

In [45]:
for value, subtable in subtables.items():
    filename = f'./data/{value}.csv'
    subtable.to_csv(filename, index=False)
    print(f"Guardado: {filename}")

Guardado: ./data/Average population - total.csv
Guardado: ./data/Net migration plus statistical adjustment.csv
Guardado: ./data/Crude rate of net migration plus statistical adjustment.csv
Guardado: ./data/Deaths - total.csv
Guardado: ./data/Average population - females.csv
Guardado: ./data/Deaths - females.csv
Guardado: ./data/Population on 1 January - females.csv
Guardado: ./data/Live births - females.csv
Guardado: ./data/Crude birth rate.csv
Guardado: ./data/Crude death rate.csv
Guardado: ./data/Total population change.csv
Guardado: ./data/Crude rate of total population change.csv
Guardado: ./data/Population on 1 January - total.csv
Guardado: ./data/Live births - total.csv
Guardado: ./data/Average population - males.csv
Guardado: ./data/Deaths - males.csv
Guardado: ./data/Sum of immigration and emigration plus statistical adjustment (migration turnover plus statistical adjustment).csv

FileNotFoundError: [Errno 2] No such file or directory: './data/Crude rate of the sum of immigration and emigration plus statistical adjustment (Crude Rate of migration turnover plus statistical adjustment).csv'